### ISSUE TITLE
ListView broken on WP8.1?

### ISSUE THREAD

**Issue by agolia** [winjs/winjs#1031]
When attempting to use the ListView with data binding control on Windows Phone 8.1 I hit the following exception...

TypeError: Unable to get property 'classList' of undefined or null reference
   at addClass (ms-appx://WinJS/js/WinJS.js:5413:9)
   at ListView_setupInternalTree (ms-appx://WinJS/js/WinJS.js:46950:21)
   at ListView_ctor (ms-appx://WinJS/js/WinJS.js:45709:17)
   at activate2 (ms-appx://WinJS/js/WinJS.js:9246:17)
   at Promise_ctor (ms-appx://WinJS/js/WinJS.js:2499:17)
   at activate (ms-appx://WinJS/js/WinJS.js:9218:9)
   at processAllImpl2 (ms-appx://WinJS/js/WinJS.js:9313:21)
   at Promise_ctor (ms-appx://WinJS/js/WinJS.js:2499:17)
   at processAllImpl (ms-appx://WinJS/js/WinJS.js:9257:9)
   at processAll (ms-appx://WinJS/js/WinJS.js:9373:13)

**Comment by rigdern** [comment]
Can you provide a page/app that repros this bug? You can share the reduced repro on OneDrive as described on our [wiki](https://github.com/winjs/winjs/wiki/How-to-share-repros-of-issues-with-WinJS#sharing-videos-and-full-code-samples) (look at the "Sharing Videos and full Code Samples" section).

**Comment by tnevda** [comment]
I'm not sure but I think it's the same issue with the one i have on https://github.com/winjs/winjs/issues/1005 .

**Comment by jseanxu** [comment]
Please respond to this issue or open a new issue with a repro.
