### ISSUE TITLE
Error at tfw start

### ISSUE THREAD

**Issue by amiceli** [winjs/winjs#1185]
When I run the command tfw start, I've an error : 

    vector.release();
    TypeError: undefined is not a function

The full output of the command is : 

    util.print: Use console.log instead
    Running "ts:build" (ts) task
    util.print: Use console.log instead
    Compiling...
    util.print: Use console.log instead
    Fast compile will not work when --out is specified. Ignoring fast compilation
    util.print: Use console.log instead
    Using tsc v1.0.1
    util.print: Use console.log instead
    /home/toni/Documents/ts/framework/testProject/node_modules/grunt-ts/node_modules/typescript/bin/tsc.js:906
                            vector.release();
                                   ^
    TypeError: undefined is not a function
        at BitMatrixImpl.release (/home/toni/Documents/ts/framework/testProject/node_modules/grunt-ts/node_modules/typescript/bin/tsc.js:906:32)
        at PullInstantiatedTypeReferenceSymbol.PullTypeSymbol.wrapsSomeTypeParameterIntoInfinitelyExpandingTypeReference (/home/toni/Documents/ts/framework/testProject/node_modules/grunt-ts/node_modules/typescript/bin/tsc.js:38021:26)
        at PullInstantiatedTypeReferenceSymbol.getGenerativeTypeClassification (/home/toni/Documents/ts/framework/testProject/node_modules/grunt-ts/node_modules/typescript/bin/tsc.js:56587:30)
        at PullTypeEnclosingTypeWalker.getGenerativeClassification (/home/toni/Documents/ts/framework/testProject/node_modules/grunt-ts/node_modules/typescript/bin/tsc.js:38846:36)
        at PullTypeResolutionContext.oneOfClassificationsIsInfinitelyExpanding (/home/toni/Documents/ts/framework/testProject/node_modules/grunt-ts/node_modules/typescript/bin/tsc.js:39598:71)
        at PullTypeResolver.sourceIsRelatableToTargetInEnclosingTypes (/home/toni/Documents/ts/framework/testProject/node_modules/grunt-ts/node_modules/typescript/bin/tsc.js:48151:29)
        at PullTypeResolver.signatureIsRelatableToTargetWorker (/home/toni/Documents/ts/framework/testProject/node_modules/grunt-ts/node_modules/typescript/bin/tsc.js:48818:52)
        at PullTypeResolver.signatureIsRelatableToTarget (/home/toni/Documents/ts/framework/testProject/node_modules/grunt-ts/node_modules/typescript/bin/tsc.js:48776:36)
        at PullTypeResolver.signatureGroupIsRelatableToTarget (/home/toni/Documents/ts/framework/testProject/node_modules/grunt-ts/node_modules/typescript/bin/tsc.js:48743:61)
        at PullTypeResolver.sourceCallSignaturesAreRelatableToTargetCallSignatures (/home/toni/Documents/ts/framework/testProject/node_modules/grunt-ts/node_modules/typescript/bin/tsc.js:48590:27)
        at PullTypeResolver.sourceIsRelatableToTargetWorker (/home/toni/Documents/ts/framework/testProject/node_modules/grunt-ts/node_modules/typescript/bin/tsc.js:48329:23)
        at PullTypeResolver.sourceIsRelatableToTarget (/home/toni/Documents/ts/framework/testProject/node_modules/grunt-ts/node_modules/typescript/bin/tsc.js:48305:36)
        at PullTypeResolver.sourceIsRelatableToTargetInEnclosingTypes (/home/toni/Documents/ts/framework/testProject/node_modules/grunt-ts/node_modules/typescript/bin/tsc.js:48156:25)
        at PullTypeResolver.sourcePropertyIsRelatableToTargetProperty (/home/toni/Documents/ts/framework/testProject/node_modules/grunt-ts/node_modules/typescript/bin/tsc.js:48559:66)
        at PullTypeResolver.sourceMembersAreRelatableToTargetMembers (/home/toni/Documents/ts/framework/testProject/node_modules/grunt-ts/node_modules/typescript/bin/tsc.js:48368:27)
        at PullTypeResolver.sourceIsRelatableToTargetWorker (/home/toni/Documents/ts/framework/testProject/node_modules/grunt-ts/node_modules/typescript/bin/tsc.js:48325:46)
        at PullTypeResolver.sourceIsRelatableToTarget (/home/toni/Documents/ts/framework/testProject/node_modules/grunt-ts/node_modules/typescript/bin/tsc.js:48305:36)
        at PullTypeResolver.sourceIsRelatableToTargetInEnclosingTypes (/home/toni/Documents/ts/framework/testProject/node_modules/grunt-ts/node_modules/typescript/bin/tsc.js:48156:25)
        at /home/toni/Documents/ts/framework/testProject/node_modules/grunt-ts/node_modules/typescript/bin/tsc.js:48831:52
        at PullInstantiatedSignatureSymbol.PullSignatureSymbol.forAllCorrespondingParameterTypesInThisAndOtherSignature (/home/toni/Documents/ts/framework/testProject/node_modules/grunt-ts/node_modules/typescript/bin/tsc.js:36729:22)
        at PullTypeResolver.signatureIsRelatableToTargetWorker (/home/toni/Documents/ts/framework/testProject/node_modules/grunt-ts/node_modules/typescript/bin/tsc.js:48829:30)
        at PullTypeResolver.signatureIsRelatableToTarget (/home/toni/Documents/ts/framework/testProject/node_modules/grunt-ts/node_modules/typescript/bin/tsc.js:48776:36)
        at PullTypeResolver.signatureGroupIsRelatableToTarget (/home/toni/Documents/ts/framework/testProject/node_modules/grunt-ts/node_modules/typescript/bin/tsc.js:48743:61)
        at PullTypeResolver.sourceCallSignaturesAreRelatableToTargetCallSignatures (/home/toni/Documents/ts/framework/testProject/node_modules/grunt-ts/node_modules/typescript/bin/tsc.js:48590:27)
        at PullTypeResolver.sourceIsRelatableToTargetWorker (/home/toni/Documents/ts/framework/testProject/node_modules/grunt-ts/node_modules/typescript/bin/tsc.js:48329:23)
        at PullTypeResolver.sourceIsRelatableToTarget (/home/toni/Documents/ts/framework/testProject/node_modules/grunt-ts/node_modules/typescript/bin/tsc.js:48305:36)
        at PullTypeResolver.sourceIsRelatableToTargetInEnclosingTypes (/home/toni/Documents/ts/framework/testProject/node_modules/grunt-ts/node_modules/typescript/bin/tsc.js:48156:25)
        at PullTypeResolver.sourcePropertyIsRelatableToTargetProperty (/home/toni/Documents/ts/framework/testProject/node_modules/grunt-ts/node_modules/typescript/bin/tsc.js:48559:66)
        at PullTypeResolver.sourcePropertyIsAssignableToTargetProperty (/home/toni/Documents/ts/framework/testProject/node_modules/grunt-ts/node_modules/typescript/bin/tsc.js:48085:69)
        at PullTypeResolver.typeCheckIfTypeExtendsType (/home/toni/Documents/ts/framework/testProject/node_modules/grunt-ts/node_modules/typescript/bin/tsc.js:50257:45)
        at /home/toni/Documents/ts/framework/testProject/node_modules/grunt-ts/node_modules/typescript/bin/tsc.js:50427:34
        at Function.PullTypeResolver.typeCheck (/home/toni/Documents/ts/framework/testProject/node_modules/grunt-ts/node_modules/typescript/bin/tsc.js:49358:21)
        at TypeScriptCompiler.getSemanticDiagnostics (/home/toni/Documents/ts/framework/testProject/node_modules/grunt-ts/node_modules/typescript/bin/tsc.js:55508:41)
        at CompilerIterator.moveNextSemanticsPhase (/home/toni/Documents/ts/framework/testProject/node_modules/grunt-ts/node_modules/typescript/bin/tsc.js:56137:45)
        at CompilerIterator.moveNextInternal (/home/toni/Documents/ts/framework/testProject/node_modules/grunt-ts/node_modules/typescript/bin/tsc.js:56087:33)
        at CompilerIterator.moveNext (/home/toni/Documents/ts/framework/testProject/node_modules/grunt-ts/node_modules/typescript/bin/tsc.js:56062:25)
        at BatchCompiler.compile (/home/toni/Documents/ts/framework/testProject/node_modules/grunt-ts/node_modules/typescript/bin/tsc.js:62412:20)
        at BatchCompiler.batchCompile (/home/toni/Documents/ts/framework/testProject/node_modules/grunt-ts/node_modules/typescript/bin/tsc.js:62251:22)
        at TypeScript (/home/toni/Documents/ts/framework/testProject/node_modules/grunt-ts/node_modules/typescript/bin/tsc.js:62928:11)
        at Object.<anonymous> (/home/toni/Documents/ts/framework/testProject/node_modules/grunt-ts/node_modules/typescript/bin/tsc.js:62929:3)
        at Module._compile (module.js:460:26)
        at Object.Module._extensions..js (module.js:478:10)
        at Module.load (module.js:355:32)
        at Function.Module._load (module.js:310:12)
        at Module.require (module.js:365:17)
        at require (module.js:384:17)
        at Object.<anonymous> (/home/toni/Documents/ts/framework/testProject/node_modules/grunt-ts/node_modules/typescript/bin/tsc:2:1)
        at Module._compile (module.js:460:26)
        at Object.Module._extensions..js (module.js:478:10)
        at Module.load (module.js:355:32)
        at Function.Module._load (module.js:310:12)
        at Function.Module.runMain (module.js:501:10)
        at startup (node.js:129:16)
        at node.js:814:3
    util.print: Use console.log instead

    util.print: Use console.log instead
    >> Error: tsc return code: 1
    util.print: Use console.log instead
    Warning: Task "ts:build" failed. Use --force to continue.
    util.print: Use console.log instead

    util.print: Use console.log instead
    Aborted due to warnings.
    util.print: Use console.log instead

    util.print: Use console.log instead
    npmutil.print: Use console.log instead
     util.print: Use console.log instead
    ERR!util.print: Use console.log instead
     Linux 3.16.0-34-generic
    util.print: Use console.log instead
    npmutil.print: Use console.log instead
     ERR!util.print: Use console.log instead
     argvutil.print: Use console.log instead
     "/usr/local/bin/node" "/usr/local/bin/npm" "start"
    npm ERR!util.print: Use console.log instead
     node v0.12.2
    util.print: Use console.log instead
    npm util.print: Use console.log instead
    ERR! util.print: Use console.log instead
    npm util.print: Use console.log instead
     v2.7.4
    npm ERR! codeutil.print: Use console.log instead
     ELIFECYCLE
    util.print: Use console.log instead
    npmutil.print: Use console.log instead
     ERR!util.print: Use console.log instead
     my-app@0.0.0 prestart: `node node_modules/grunt-cli/bin/grunt`
    npm util.print: Use console.log instead
    ERR! Exit status 3
    util.print: Use console.log instead
    npm ERR! 
    util.print: Use console.log instead
    npm ERR!util.print: Use console.log instead
     Failed at the my-app@0.0.0 prestart script 'node node_modules/grunt-cli/bin/grunt'.
    util.print: Use console.log instead
    npm ERR!util.print: Use console.log instead
     This is most likely a problem with the my-app package,
    npm util.print: Use console.log instead
    ERR! not with npm itself.
    npmutil.print: Use console.log instead
     ERR!util.print: Use console.log instead
     Tell the author that this fails on your system:
    npm util.print: Use console.log instead
    ERR!     node node_modules/grunt-cli/bin/grunt
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls my-app
    npm ERR! There is likely additional logging output above.
    util.print: Use console.log instead

    util.print: Use console.log instead
    npm util.print: Use console.log instead
    ERR! Please include the following file with any support request:
    npm ERR!     /home/toni/Documents/ts/framework/testProject/npm-debug.log
    util.print: Use console.log instead
    child process exited with code 1

**Comment by amiceli** [comment]
I'm so sorry, i was on the wrong repository ...
