### ISSUE TITLE
WinJS.UI.AppBar - compact & Windows.UI.Popups.MessageDialog - exception

### ISSUE THREAD

**Issue by mesju** [winjs/winjs#1523]
I implemented a Win10 UWP App (WinJS 4.4.0), with an WinJS.UI.AppBar. The "closedDisplayMode" is set to compact. One of the AppBar buttons opens a Windows.UI.Popups.MessageDialog. 

```html
<div data-win-control="WinJS.UI.AppBar" data-win-options="{ closedDisplayMode : 'compact' }">
            <button data-win-control="WinJS.UI.Command" data-win-options="{ id: 'cmdEdit', label: 'edit', icon: 'edit' }"></button>
</div>
```
```javascript
var cmdEditCtrl = document.getElementById('cmdEdit').winControl;
cmdEditCtrl.addEventListener('click', function () {
  var md = new Windows.UI.Popups.MessageDialog('This is a message dialog', 'MessageDialog');
  md.commands.append(new Windows.UI.Popups.UICommand('Close'));
  md.showAsync();
});
```
Then following exception is thrown when the AppBar is opened to "full" by clicking '...' and then clicking the edit button, which opens the MessageDialog:

Exception is about to be caught by JavaScript library code at line 38793, column 17 in ms-appx://8f49808f-476e-49d2-b6bf-5aed30f555ba/WinJS/js/ui.js
0x8001010d - JavaScript runtime error: An outgoing call cannot be made since the application is dispatching an input-synchronous call.

**Comment by jdalton** [comment]
May be related to #1408.

**Comment by mesju** [comment]
Yes.

It's the same exception I got:

"WinRTError: An outgoing call cannot be made since the application is dispatching an input-synchronous call.

   at get exports._KeyboardInfo._extraOccluded (ms-appx://8f49808f-476e-49d2-b6bf-5aed30f555ba/WinJS/js/ui.js:38793:17)
   at get exports._KeyboardInfo._visibleDocHeight (ms-appx://8f49808f-476e-49d2-b6bf-5aed30f555ba/WinJS/js/ui.js:38811:13)
   at get exports._KeyboardInfo._layoutViewportCoords (ms-appx://8f49808f-476e-49d2-b6bf-5aed30f555ba/WinJS/js/ui.js:38887:13)
   at onClose (ms-appx://8f49808f-476e-49d2-b6bf-5aed30f555ba/WinJS/js/ui.js:55203:25)
   at Anonymous function (ms-appx://8f49808f-476e-49d2-b6bf-5aed30f555ba/WinJS/js/ui.js:43562:25)
   at notifySuccess (ms-appx://8f49808f-476e-49d2-b6bf-5aed30f555ba/WinJS/js/base.js:2110:21)
   at state_success_notify.enter (ms-appx://8f49808f-476e-49d2-b6bf-5aed30f555ba/WinJS/js/base.js:1792:21)
   at _run (ms-appx://8f49808f-476e-49d2-b6bf-5aed30f555ba/WinJS/js/base.js:2008:17)
   at _completed (ms-appx://8f49808f-476e-49d2-b6bf-5aed30f555ba/WinJS/js"
